# Generated by Django 3.0.3 on 2021-07-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrossBag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Name', models.CharField(max_length=100)),
                ('Item_Quantity', models.IntegerField()),
                ('Item_status', models.CharField(choices=[('1', 'PENDING'), ('2', 'BOUGHT'), ('3', 'NOT AVAILABLE')], max_length=25)),
                ('Date', models.DateField()),
            ],
        ),
    ]
